# Generated by Django 2.0 on 2020-07-08 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Blog_type',
            new_name='blog_type',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='last_updated',
            new_name='last_updated_time',
        ),
    ]
