# Generated by Django 2.0 on 2020-07-06 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_creat_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='creat_time',
            new_name='created_time',
        ),
    ]
